version: '2.4'
services:
  server:
    image: cluedin/cluedin-server:${TAG}
    platform: windows
    env_file:
    - ./pki/certs/server-certs.vars
    - ./var-files/server.vars
    environment:
    - Models.Enabled=false
    - EmailServer=smtp.mailtrap.io
    - EmailPort=2525
    - EmailDisplayName=CluedIn
    - EmailSender=app@cluedin-test.online
    - EmailUserName
    - EmailPassword
    - KEY
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - ./components:c:\components
    depends_on:
    - sqlserver
    - redis
    - rabbitmq
    - neo4j
    - elasticsearch

  app:
    image: cluedin/app:${TAG}
    platform: linux
    entrypoint:
    - sh
    - -c
    - cat /certs/root.crt >> /etc/ssl/certs/ca-certificates.crt && dotnet CluedIn.App.dll
    env_file:
    - ./var-files/app.vars
    environment:

    - EmailSettings__SpecifiedPickupDirectory=/emails
    # If you want to use a mail server - comment out the env var above 
    # and add configuration below
    # - EmailSettings__SmtpUserName=??
    # - EmailSettings__SmtpPassword=??
    # - EmailSettings__SmtpHost=
    # - EmailSettings__SmtpPort=25

    ports:
    - "443:443"
    volumes:
    - ./pki/certs:/certs
    - ./emails:/emails

# Dependencies
  neo4j:
    image: cluedin/neo4j:${TAG}
    platform: linux
    environment:
    - NEO4J_AUTH=none
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_EDITION=community
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - neo4j:/data

  elasticsearch:
    image: cluedin/elasticsearch:${TAG}
    platform: linux
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data

  sqlserver:
    image: cluedin/sqlserver:${TAG}
    platform: linux
    command: ["sh","-c","echo '127.0.0.1 localhost'>> /etc/hosts; /init/init.sh"]
    environment:
    - MSSQL_DATA_DIR=/mssql-data
    mem_limit: 3G
    ports:
    - "1433:1433"
    volumes:
    - sqlserver:/mssql-data

  openrefine:
    image: cluedin/openrefine:${TAG}
    entrypoint:
    - sh
    - -c
    - cp /config/* /app/ -f && /app/refine
    platform: linux
    ports:
    - "3333:3333"
    mem_limit: 2G
    volumes:
    - ./config-files:/config

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    platform: linux
    ports:
    - "5672:5672"
    - "15672:15672"
    hostname: cluedin-dev
    environment: 
    - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.95
    - RABBITMQ_LOOPBACK_USERS=none

  redis:
    image: redis:5.0-alpine
    platform: linux
    ports:
    - "6379:6379"


# Useful tools
  seq:
    image: datalust/seq:5
    platform: linux
    restart: unless-stopped
    environment:
    - ACCEPT_EULA=Y
    ports:
    - "3200:80"
    - "5341:5341"

volumes:
  sqlserver:
  elasticsearch:
  neo4j: